### ISSUE TITLE
Failed to install on MacOS

### ISSUE THREAD

**Issue by pzelasko** [csukuangfj/kaldi_native_io#20]
There seems to be an error with finding include directory / files, not sure why.

```
$ pip install kaldi_native_io
Collecting kaldi_native_io
  Using cached kaldi_native_io-1.3.tar.gz (123 kB)
Requirement already satisfied: numpy in /Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages (from kaldi_native_io) (1.21.5)
Building wheels for collected packages: kaldi-native-io
  Building wheel for kaldi-native-io (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/pzelasko/miniconda3/envs/lhotse/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py'"'"'; __file__='"'"'/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-wheel-r1dnbl9h
       cwd: /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/
  Complete output (100 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.0-arm64-3.8
  creating build/lib.macosx-11.0-arm64-3.8/kaldi_native_io
  copying kaldi_native_io/python/kaldi_native_io/__init__.py -> build/lib.macosx-11.0-arm64-3.8/kaldi_native_io
  copying kaldi_native_io/python/kaldi_native_io/table_types.py -> build/lib.macosx-11.0-arm64-3.8/kaldi_native_io
  running build_ext
  For fast compilation, run:
  export KALDI_NATIVE_IO_MAKE_ARGS="-j"; python setup.py install
  Setting PYTHON_EXECUTABLE to /Users/pzelasko/miniconda3/envs/lhotse/bin/python
  build command is:
  
              cd build/temp.macosx-11.0-arm64-3.8
  
              cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/Users/pzelasko/miniconda3/envs/lhotse/bin/python /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530
  
              make  _kaldi_native_io
  
  -- The CXX compiler identification is AppleClang 13.0.0.13000029
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading pybind11
  -- pybind11 is downloaded to /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/build/temp.macosx-11.0-arm64-3.8/_deps/pybind11-src
  -- pybind11 v2.6.0
  CMake Warning (dev) at /Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.22/Modules/CMakeDependentOption.cmake:84 (message):
    Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
    Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.
  Call Stack (most recent call first):
    build/temp.macosx-11.0-arm64-3.8/_deps/pybind11-src/CMakeLists.txt:91 (cmake_dependent_option)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found PythonInterp: /Users/pzelasko/miniconda3/envs/lhotse/bin/python (found version "3.8.12")
  -- Found PythonLibs: /Users/pzelasko/miniconda3/envs/lhotse/lib/libpython3.8.dylib
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Performing Test HAS_FLTO_THIN
  -- Performing Test HAS_FLTO_THIN - Success
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/build/temp.macosx-11.0-arm64-3.8
  [  4%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/compressed-matrix.cc.o
  [  9%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/io-funcs.cc.o
  [ 14%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/kaldi-holder.cc.o
  [ 19%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/kaldi-io.cc.o
  In file included from /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/kaldi_native_io/csrc/kaldi-io.cc:13:
  /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/kaldi_native_io/csrc/kaldi-pipebuf.h:31:10: fatal error: 'kaldi_native_io/csrc/util/basic-filebuf.h' file not found
  #include "kaldi_native_io/csrc/util/basic-filebuf.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  make[3]: *** [kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/kaldi-io.cc.o] Error 1
  make[2]: *** [kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/all] Error 2
  make[1]: *** [kaldi_native_io/python/csrc/CMakeFiles/_kaldi_native_io.dir/rule] Error 2
  make: *** [_kaldi_native_io] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py", line 104, in <module>
      setuptools.setup(
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py", line 62, in build_extension
      raise Exception(
  Exception:
  Build kaldi_native_io failed. Please check the error message.
  You can ask for help by creating an issue on GitHub.
  
  Click:
     https://github.com/csukuangfj/kaldi_native_io/issues/new
  
  ----------------------------------------
  ERROR: Failed building wheel for kaldi-native-io
  Running setup.py clean for kaldi-native-io
Failed to build kaldi-native-io
Installing collected packages: kaldi-native-io
    Running setup.py install for kaldi-native-io ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/pzelasko/miniconda3/envs/lhotse/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py'"'"'; __file__='"'"'/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-record-pqbrsbkj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/pzelasko/miniconda3/envs/lhotse/include/python3.8/kaldi-native-io
         cwd: /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/
    Complete output (102 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11.0-arm64-3.8
    creating build/lib.macosx-11.0-arm64-3.8/kaldi_native_io
    copying kaldi_native_io/python/kaldi_native_io/__init__.py -> build/lib.macosx-11.0-arm64-3.8/kaldi_native_io
    copying kaldi_native_io/python/kaldi_native_io/table_types.py -> build/lib.macosx-11.0-arm64-3.8/kaldi_native_io
    running build_ext
    For fast compilation, run:
    export KALDI_NATIVE_IO_MAKE_ARGS="-j"; python setup.py install
    Setting PYTHON_EXECUTABLE to /Users/pzelasko/miniconda3/envs/lhotse/bin/python
    build command is:
    
                cd build/temp.macosx-11.0-arm64-3.8
    
                cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/Users/pzelasko/miniconda3/envs/lhotse/bin/python /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530
    
                make  _kaldi_native_io
    
    -- The CXX compiler identification is AppleClang 13.0.0.13000029
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Downloading pybind11
    -- pybind11 is downloaded to /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/build/temp.macosx-11.0-arm64-3.8/_deps/pybind11-src
    -- pybind11 v2.6.0
    CMake Warning (dev) at /Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.22/Modules/CMakeDependentOption.cmake:84 (message):
      Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
      Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    Call Stack (most recent call first):
      build/temp.macosx-11.0-arm64-3.8/_deps/pybind11-src/CMakeLists.txt:91 (cmake_dependent_option)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found PythonInterp: /Users/pzelasko/miniconda3/envs/lhotse/bin/python (found version "3.8.12")
    -- Found PythonLibs: /Users/pzelasko/miniconda3/envs/lhotse/lib/libpython3.8.dylib
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Performing Test HAS_FLTO_THIN
    -- Performing Test HAS_FLTO_THIN - Success
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/build/temp.macosx-11.0-arm64-3.8
    [  4%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/compressed-matrix.cc.o
    [  9%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/io-funcs.cc.o
    [ 14%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/kaldi-holder.cc.o
    [ 19%] Building CXX object kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/kaldi-io.cc.o
    In file included from /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/kaldi_native_io/csrc/kaldi-io.cc:13:
    /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/kaldi_native_io/csrc/kaldi-pipebuf.h:31:10: fatal error: 'kaldi_native_io/csrc/util/basic-filebuf.h' file not found
    #include "kaldi_native_io/csrc/util/basic-filebuf.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make[3]: *** [kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/kaldi-io.cc.o] Error 1
    make[2]: *** [kaldi_native_io/csrc/CMakeFiles/kaldi_native_io_core.dir/all] Error 2
    make[1]: *** [kaldi_native_io/python/csrc/CMakeFiles/_kaldi_native_io.dir/rule] Error 2
    make: *** [_kaldi_native_io] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py", line 104, in <module>
        setuptools.setup(
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/Users/pzelasko/miniconda3/envs/lhotse/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py", line 62, in build_extension
        raise Exception(
    Exception:
    Build kaldi_native_io failed. Please check the error message.
    You can ask for help by creating an issue on GitHub.
    
    Click:
       https://github.com/csukuangfj/kaldi_native_io/issues/new
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/pzelasko/miniconda3/envs/lhotse/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py'"'"'; __file__='"'"'/private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-install-eohs00ou/kaldi-native-io_256b73d789a44e81a34963d73ec1e530/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/py/z3fbmg3j3x9g83khfx3gnf680000gn/T/pip-record-pqbrsbkj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/pzelasko/miniconda3/envs/lhotse/include/python3.8/kaldi-native-io Check the logs for full command output.
```

**Comment by csukuangfj** [comment]
Could you try

```bash
git clone https://github.com/csukuangfj/kaldi_native_io
cd kaldi_native_io
mkdir build
cd build
cmake ..
make -j
```

And then do
```
export PYTHONPATH=/path/to/kaldi_native_io/kaldi_native_io/python:$PYTHONPATH
export PYTHONPATH=/path/to/kaldi_native_io/build/lib:$PYTHONPATH
```

Then you should be able to use `import kaldi_native_io` in your python code.

---

Will look into it why it fails to install when using `pip install`.

**Comment by csukuangfj** [comment]
Please install kaldi_native_io >= v1.4, which should be working for macOS.

**Comment by pzelasko** [comment]
Thanks, it seems to be working! Closing the issue.
