### ISSUE TITLE
does not work on MacOS even after successful install

### ISSUE THREAD

**Issue by jtrmal** [csukuangfj/kaldi_native_io#28]
```
pip3 install kaldi-native-io
```

after successful install I still cannot run:

```
$ lhotse kaldi import data/dev40/ 16000 data/dev40/lhotse
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/jtrmal/projects/lhotse/lhotse/kaldi.py", line 50, in get_duration
    import kaldi_native_io
  File "/usr/local/lib/python3.9/site-packages/kaldi_native_io/__init__.py", line 1, in <module>
    from _kaldi_native_io import (
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/_kaldi_native_io.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libkaldi_native_io_core.dylib
  Referenced from: /usr/local/lib/python3.9/site-packages/_kaldi_native_io.cpython-39-darwin.so
  Reason: tried: '$ORIGIN/libkaldi_native_io_core.dylib' (no such file), '/private/var/folders/hk/9m49z_f10rs8mk4k3106h6sh0000gn/T/pip-install-jkps8j1v/kaldi-native-io_fdd6e7c5470d462bba477456bbbb1056/build/temp.macosx-12-x86_64-3.9/lib/libkaldi_native_io_core.dylib' (no such file), '$ORIGIN/libkaldi_native_io_core.dylib' (no such file), '/private/var/folders/hk/9m49z_f10rs8mk4k3106h6sh0000gn/T/pip-install-jkps8j1v/kaldi-native-io_fdd6e7c5470d462bba477456bbbb1056/build/temp.macosx-12-x86_64-3.9/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/local/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/local/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/local/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/lib/libkaldi_native_io_core.dylib' (no such file)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/lhotse", line 33, in <module>
    sys.exit(load_entry_point('lhotse', 'console_scripts', 'lhotse')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jtrmal/projects/lhotse/lhotse/bin/modes/kaldi.py", line 56, in import_
    recording_set, maybe_supervision_set, maybe_feature_set = load_kaldi_data_dir(
  File "/Users/jtrmal/projects/lhotse/lhotse/kaldi.py", line 99, in load_kaldi_data_dir
    durations = dict(zip(recordings.keys(), dur_vals))
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/_kaldi_native_io.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libkaldi_native_io_core.dylib
  Referenced from: /usr/local/lib/python3.9/site-packages/_kaldi_native_io.cpython-39-darwin.so
  Reason: tried: '$ORIGIN/libkaldi_native_io_core.dylib' (no such file), '/private/var/folders/hk/9m49z_f10rs8mk4k3106h6sh0000gn/T/pip-install-jkps8j1v/kaldi-native-io_fdd6e7c5470d462bba477456bbbb1056/build/temp.macosx-12-x86_64-3.9/lib/libkaldi_native_io_core.dylib' (no such file), '$ORIGIN/libkaldi_native_io_core.dylib' (no such file), '/private/var/folders/hk/9m49z_f10rs8mk4k3106h6sh0000gn/T/pip-install-jkps8j1v/kaldi-native-io_fdd6e7c5470d462bba477456bbbb1056/build/temp.macosx-12-x86_64-3.9/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/local/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/local/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/local/lib/libkaldi_native_io_core.dylib' (no such file), '/usr/lib/libkaldi_native_io_core.dylib' (no such file)
```

Even after copying the dynlib (`/usr/local/lib/python3.9/site-packages/libkaldi_native_io_core.dylib`) to `/usr/local/lib` I'm getting another error

```
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/jtrmal/projects/lhotse/lhotse/kaldi.py", line 50, in get_duration
    import kaldi_native_io
  File "/usr/local/lib/python3.9/site-packages/kaldi_native_io/__init__.py", line 1, in <module>
    from _kaldi_native_io import (
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/_kaldi_native_io.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN7kaldiio9SubMatrixIdEC1ERKNS_10MatrixBaseIdEEiiii'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/lhotse", line 33, in <module>
    sys.exit(load_entry_point('lhotse', 'console_scripts', 'lhotse')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jtrmal/projects/lhotse/lhotse/bin/modes/kaldi.py", line 56, in import_
    recording_set, maybe_supervision_set, maybe_feature_set = load_kaldi_data_dir(
  File "/Users/jtrmal/projects/lhotse/lhotse/kaldi.py", line 99, in load_kaldi_data_dir
    durations = dict(zip(recordings.keys(), dur_vals))
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/_kaldi_native_io.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN7kaldiio9SubMatrixIdEC1ERKNS_10MatrixBaseIdEEiiii'
```

(the symbol is demangled to `_kaldiio::SubMatrix<double>::SubMatrix(kaldiio::MatrixBase<double> const&, int, int, int, int)`)

**Comment by jtrmal** [comment]
I tested manual install and setting the paths like outlined in #20 but that didn't resolve issue for me (still have the `: symbol not found in flat namespace` error present)

**Comment by jtrmal** [comment]
I resolved the issue by explicit instantiation of the SubMatrix<> template for float and double:

```
$ git diff
diff --git a/kaldi_native_io/csrc/kaldi-matrix.cc b/kaldi_native_io/csrc/kaldi-matrix.cc
index fceac04..fcdd4ec 100644
--- a/kaldi_native_io/csrc/kaldi-matrix.cc
+++ b/kaldi_native_io/csrc/kaldi-matrix.cc
@@ -653,5 +653,7 @@ template class Matrix<float>;
 template class Matrix<double>;
 template class MatrixBase<float>;
 template class MatrixBase<double>;
+template class SubMatrix<float>;
+template class SubMatrix<double>;

 }  // namespace kaldiio
 ```
